date_folder_list: # write None if including all files
  - "20230626"

individual_list: # write None if including all files
  - "1"

joints:
  'Right shoulder': 1
  'Left shoulder': 2
  'Right elbow': 3
  'Left elbow': 4
  'Right wrist': 5
  'Left wrist': 6
  'Right hip': 7
  'Left hip': 8
  'Right knee': 9
  'Left knee': 10
  'Right ankle': 11
  'Left ankle': 12
  'Right toe': 13
  'Left toe': 14


merge_point:
  'Right shoulder': ['Right shoulder 1', 'Right shoulder 2', 'Right shoulder 3']
  'Left shoulder': ['Left shoulder 1', 'Left shoulder 2', 'Left shoulder 3']
  'Right elbow': ['Right elbow 1', 'Right elbow 2', 'Right elbow 3']
  'Left elbow': ['Left elbow 1', 'Left elbow 2', 'Left elbow 3']
  'Right wrist': ['Right wrist 1', 'Right wrist 2', 'Right wrist 3']
  'Left wrist': ['Left wrist 1', 'Left wrist 2', 'Left wrist 3']
  'Right hip': ['Right hip 1', 'Right hip 2', 'Right hip 3']
  'Left hip': ['Left hip 1', 'Left hip 2', 'Left hip 3']
  'Right knee': ['Right knee 1', 'Right knee 2', 'Right knee 3']
  'Left knee': ['Left knee 1', 'Left knee 2', 'Left knee 3']
  'Right ankle': ['Right ankle 1', 'Right ankle 2', 'Right ankle 3', 'Right ankle 4', 'Right heel']
  'Left ankle': ['Left ankle 1', 'Left ankle 2', 'Left ankle 3', 'Left ankle 4', 'Left heel']
  'Right toe': ['Right toe 1', 'Right toe 2', 'Right toe 3']
  'Left toe': ['Left toe 1', 'Left toe 2', 'Left toe 3']

frequency: 10  # Hz

add_noise: False # False or ratio (float)

flip: False # False or axis (int), 0 is x, 1 is y, 2 is z

axis_range: 32767 # The coordinate axis range from - to + for the keypoints

heatmap_shape: [20, 20, 18]

link_limit:
  -
    - [1,3]
    -
  -
    - [3,5]
    -
  -
    - [2,4]
    -
  -
    - [4,6]
    -
  -
    - [1,8]
    -
  -
    - [2,7]
    -
  -
    - [7,8]
    -
  -
    - [7,9]
    -
  -
    - [9,11]
    -
  -
    - [13,11]
    -
  -
    - [8,10]
    -
  -
    - [10,12]
    -
  -
    - [12,14]
    -
