model:
  - Conv3dBlock:
      name: layer_1
      filters: 128
      kernel_size:
        - 2
        - 2
        - 2
      strides:
        - 2
        - 1
        - 1
      padding: same
      activation: leaky_relu
      dropout: .2

  - Conv3dBlock:
      name: layer_2
      filters: 256
      kernel_size:
        - 2
        - 3
        - 2
      strides:
        - 2
        - 2
        - 1
      padding: same
      activation: leaky_relu
      dropout: .2

  - Conv3dBlock:
      name: layer_3
      filters: 512
      kernel_size:
        - 3
        - 3
        - 2
      strides:
        - 2
        - 2
        - 1
      padding: same
      activation: leaky_relu
      dropout: .2
  - MaxPoolingBlock:
      pool_size:
        - 2
        - 1
        - 1
      padding: "valid"
      name: pool1
  - Squeeze:
      name: squeeze
      axis:
        - 1

  - Conv2dBlock:
      name: cov5
      filters: 256
      kernel_size:
        - 3
        - 4
      strides:
        - 1
        - 1
      padding: valid
      activation: tanh
      dropout: .2

  - MaxPoolingBlock:
      pool_size:
        - 2
        - 1
      padding: "valid"
      name: pool2

  - Squeeze:
      name: squeeze
      axis:
        - 1

#  - DenseBlock:
#      name: layer_44
#      flatten: False
#      reshape: None
#      unit: 32
#      activation: relu
#      dropout: .2
  - Conv1dBlock:
      name: cov6
      filters: 64
      kernel_size: 4
      strides: 1
      padding: valid
      activation: relu
      dropout: .2

  - Conv1dBlock:
      name: cov7
      filters: 3
      kernel_size: 5
      strides: 1
      padding: valid
      activation: relu
      dropout: 0

train:
  input:
    shape:
      - 10
      - 13
      - 24
  optimizer:
    Adam:
      learning_rate: 0.0001
      decay: 0.1
      clipnorm: 3
  callbacks:
    early_stopping:
      monitor: val_loss
      min_delta: 0
      patience: 3
      verbose: 0
      mode: auto
      baseline: None
      restore_best_weights: False
    csv_logger:
      filename: training_loss.csv
    save_each_epoch:
      monitor: val_loss
      verbose: 1
      save_best_only: False
      save_weights_only: True
      mode: auto
      period: 1
  loss: MAE
  batch_size: 512
  epochs: 100
  verbose: 1
  retrain: False
  shuffle: 100


