
model:
  - Conv3dBlock:
      name: layer_1
      filters: 32
      kernel_size: (3, 3, 4)
      strides: (3,2,2)
      padding: same
      activation: tanh
      dropout: 2

  - Conv3dBlock:
      name: layer_2
      filters: 128
      kernel_size: (3, 3, 4)
      strides: (3,1,2)
      padding: same
      activation: tanh
      dropout: 2

  - FlattenBlock:
      name: layer_3
      reshape: (128, 12, 3)
      activation: tanh
      dropout: 2



train:
  optimizer:
    script_path: adam
    initial_lr: 0.0001
    decay: 0.003
  callbacks:
    early_stopping:
      monitor: val_loss
      min_delta: 0
      patience: 3
      verbose: 0
      mode: auto
      baseline: None
      restore_best_weights: False
    csv_logger:
      path: 'log/training_loss'
    save_each_epoch:
      path: savepoint/
      monitor: val_loss
      verbose: 0
      save_best_only: False
      save_weights_only: True
      mode: 'auto'
      period: 1
  loss: custom_loss
  batch_size: 64
  epochs: 100


